### ISSUE TITLE
Saubere POMs

### ISSUE THREAD

**Issue by peter-mueller** [xdoo/gaia-infrastructure#2]
Parent POM von Spring Cloud verwenden (**v**Brixton.M4).

**Comment by peter-mueller** [comment]
@FabianHoltkoetter 
[Spring Boot Actuator ja/nein?](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-endpoints)

**Comment by FabianWilms** [comment]
Brauchen wir das denn? Wir haben ja schon den eureka. oder verstehe ich da was falsch?

**Comment by peter-mueller** [comment]
https://youtu.be/sbPSjI4tt10?t=46m22s

**Comment by FabianWilms** [comment]
OK, das ist schon sehr schick. Da freut sich doch bestimmt auch @xdoo über die vielen Statistiken. Kann man die Endpunkte denn auch absichern? Da sollte ja jetzt nicht jeder User drauf können.

**Comment by xdoo** [comment]
@peter-mueller und @FabianHoltkoetter - ja da freut sich @xdoo. Die kann man auch absichern. In jedem Fall über das Gateway. In Docker würde es aber auch schon ganz einfach gehen, indem man das Property <pre>management.port</pre> **nicht** auf den gleichen Wert wie <pre>server.port</pre> setzt :)

**Comment by peter-mueller** [comment]
Ich mal ein neues Ticket dafür
